SELECT user.USERNAME, IFNULL(REVIEWS_AMOUNT.AMOUNT_REVIEWS, 0) AS AMOUNT_REVIEWS FROM profit.user
LEFT JOIN (SELECT reviews.USERNAME, count(*) AMOUNT_REVIEWS 
    FROM profit.reviews
    WHERE month(reviews.REVIEW_DATE) = 5 AND day(reviews.REVIEW_DATE) = 9
    GROUP BY reviews.USERNAME)
AS REVIWS_AMOUNT 
ON USER.USERNAME = REVIWS_AMOUNT.USERNAME