SELECT * 
FROM (SELECT USERNAME, COUNT(*) OFFERS_NUMBER
	FROM profit.offer
	INNER JOIN profit.user
	ON offer.USER_ID = user.USER_ID
    WHERE DATE(CREATED_AT) >= DATE_ADD(curdate(), INTERVAL -10 DAY)
	GROUP BY USERNAME) numbers
WHERE OFFERS_NUMBER > 3