SELECT OFFER_ID, USERNAME, OFFER_NAME, DESCRIPTION, LINK, PHOTO_LINK, CREATED_AT, VALID_UNTIL, DISCOUNT
FROM profit.offer
INNER JOIN profit.user as USER
ON offer.USER_ID = user.USER_ID
WHERE USERNAME = 'yogaclass' AND DATE(CREATED_AT) = '2021-03-01'