SELECT USERNAME 
FROM (SELECT USERNAME, COUNT(*) OFFERS_NUMBER
	FROM profit.offer
	INNER JOIN profit.user
	ON offer.USER_ID = user.USER_ID
    WHERE DATE(VALID_UNTIL) > curdate()
	GROUP BY USERNAME) numbers
WHERE OFFERS_NUMBER > 3